services:
  - type: web
    name: ProjetMES-Dashboard
    env: python
    plan: free
    pythonVersion: 3.11
    build:
      command: "pip install -r requirements.txt"
    start: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
